// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkbfsehqqcjlbalynodu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrYmZzZWhxcWNqbGJhbHlub2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDUyODYsImV4cCI6MjA3MDQyMTI4Nn0.I1BAP4WO_rpzeLxIGvDoehrUYIbCQakqa056bEPWRDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});